
build:
  info: 1.0.0

loans:
  message: "Welcome to SKD Bank loans service, environment - PROD "
  contactDetails:
    name: "Sumeet Dwivedi - Developer"
    email: "sumeet@skdbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345

spring:
  datasource:
    url: jdbc:mysql://loansdb:3306/loans
    username: root
    password: root
    driver-class-name : com.mysql.cj.jdbc.Driver