
build:
  info: 1.0.0

accounts:
  message: "Welcome to SKD Bank accounts service, environment - PROD "
  contactDetails:
    name: "Sumeet Dwivedi - Developer"
    email: "sumeet@skdbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
